### ISSUE TITLE
Confusion about cv2 version

### ISSUE THREAD

**Issue by novrain99** [siatheindochinese/OnePoseDatasetCollector#1]
Hi, @siatheindochinese . 

Thanks for this tool. I am interested in OnePose and was preparing my custom datasets. So it's great to have this tool. I try to compile the code to take the pose of my object on an printed aruco board. The problem is that I always have some error about the CharucoBoard object. I am think that the problem is coming from the fact that I am using a wrong version of cv2. I started with the latest 4.7 version and had an error saying that matchImagePoints is no attribute of CharucoBoard. Then I switched to version 4.4 as noted in the original OnePose project and have another error saying that cv2.aruco has no attribute CharucoBoard. Could you please tell me the verison you used before? Thanks in advance.

**Comment by siatheindochinese** [comment]
Hello, the Python OpenCV version which this repo is tested on is `opencv-contrib-python==4.7.0.72`.

**Comment by novrain99** [comment]
Hi! Thanks for the prompt reply! It works perfectly now!
