### ISSUE TITLE
Question about the object's pose

### ISSUE THREAD

**Issue by novrain99** [siatheindochinese/OnePoseDatasetCollector#2]
Hi, @siatheindochinese . It's me again! I just took a few images of the object I am measuring and I had this confusion. I saw the coordinate which should imply the pose of the object is shown as shifted from the object. Is this normal? Maybe it's a stupid question but I am new to aruco board and the way to use it for estimating pose. Note that I am using a smaller board.
![empty](https://user-images.githubusercontent.com/111428680/229570866-453cbc39-352d-4c4f-8b5f-e2bbb275e922.png)

**Comment by siatheindochinese** [comment]
Seems like a problem with Perspective-n-Point. What camera are you using? If you are not using Intel Realsense, did you calibrate your camera and save the intrinsic matrix as a `.txt` file, put it in `configs/intrin/` and specify your intrinsics with the `--intrin` flag?

Addendum: Keep square length = 200 in your configuration for now, I will make some changes to allow the square length to vary.

Addendum 2: I must warn that OnePose does not work with Textureless objects like the one in the picture. OnePose++, on the other hand, solves the textureless problem by using LoFTR for 2D-2D matching and the idea behind LoFTR for 2D-3D matching.

**Comment by novrain99** [comment]
I am using a RealSense D435f but I didn't do anything to specify the camera's intrinsics.

**Comment by siatheindochinese** [comment]
Did you edit the `.png` file generated by the board? Print it as it is, without resizing it. The scale of the printed board matters.
And keep `sl=200` in your config for now. If you print it correctly, it should be the same size as the one shown in my examples.

**Comment by novrain99** [comment]
I tried also with the original board, and the coordinate is still not at the center of the box in the middle. The red line at the corner should be part of the coordinate.
![newempty](https://user-images.githubusercontent.com/111428680/229574350-4e670606-1a81-43a2-9f15-c262c6f1e303.png)

**Comment by novrain99** [comment]
OH, there is another modification I made and I forgot to mention. I changed the resolution form 1280, 800 to 1280, 720 since the original one is not supported by my camera(D435f) and it always return an error saying RuntimeError: Couldn't resolve requests.

**Comment by siatheindochinese** [comment]
I will look into parameterizing some hard-coded variables to see if amends the PnP problem. Your RuntimeError might be a problem with your D435f.

**Comment by novrain99** [comment]
Yes, my camera can only support up to 1280x720 and the one you used is compatible with 1280x800. I was suspecting the shift of the frame might be because of this change.
