### ISSUE TITLE
Is it possible to do it on big object?

### ISSUE THREAD

**Issue by brian2lee** [siatheindochinese/OnePoseDatasetCollector#3]
As the title mention, I'm trying to do it on a pallet. However, it's too big for a aruco board. Is it possible to do data collect using aruco board on big object? If so where do I place the board? Sorry if this is a stupid question since I am new to aruco board and pose estimation.

**Comment by siatheindochinese** [comment]
Unfortunately, my rudimentary solution is only for handheld-sized objects.

You should seek other methods based off scene localization such as ARCore/ARKit. The official OnePose Cap app in iOS might be what you need.
