### ISSUE TITLE
no attribute detectmarkers

### ISSUE THREAD

**Issue by arvindkrvartiya123** [siatheindochinese/OnePoseDatasetCollector#4]
while running detect_arucoboard_opencv.py, I'm getting cv2.aruco has no attribute 'detectMarkers'.

**Comment by arvindkrvartiya123** [comment]
After resolving above issues i got this error "objPoints, imgPoints = board.matchImagePoints(markerCorners, markerIds)
AttributeError: 'cv2.aruco.CharucoBoard' object has no attribute 'matchImagePoints'"

**Comment by siatheindochinese** [comment]
You might want to check the version of OpenCV you're using. Mine runs on `opencv-contrib-python==4.7.0.72`
